name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ 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 }}
      
      - name: Build and push the Docker image
        run: |
          docker build -t ghcr.io/deselikem/hello-docker-gcr-demo:latest .
          docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
